import { test, expect } from '@playwright/test';

test.describe('Admin Flow', () => {
    test('login, write and publish article', async ({ page }) => {
        // Debug
        page.on('console', msg => console.log(`[Browser Console] ${msg.text()}`));
        page.on('pageerror', err => console.log(`[Browser Error] ${err.message}`));

        // Mock API calls
        await page.route('**/api/auth/login', async route => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ token: 'fake-jwt-token' })
            });
        });
        await page.route('**/api/admin/categories', async route => {
            // Check if component calls /categories or /admin/categories
            // Editor.svelte calls /categories
            await route.fulfill({
                json: [{ id: 'cat1', name: 'General' }]
            });
        });
        // Also mock /categories just in case
        await page.route('**/api/categories', async route => {
            await route.fulfill({
                json: [{ id: 'cat1', name: 'General' }]
            });
        });

        await page.route('**/api/qa', async route => {
            await route.fulfill({ json: { success: true } });
        });

        // Handle image upload if needed
        await page.route('**/api/upload', async route => {
            await route.fulfill({ json: { url: 'http://placeholder.com/image.png' } });
        });

        // 1. Login
        await page.goto('/login');
        await page.fill('input[name="email"]', 'admin@example.com');
        await page.fill('input[name="password"]', 'admin123');
        await page.click('button[type="submit"]');

        // Check for error message if login failed
        const errorMsg = page.locator('.text-red-500');
        if (await errorMsg.isVisible()) {
            console.log('Login Error Visible:', await errorMsg.textContent());
        }

        // Wait for navigation to admin dashboard
        await expect(page).toHaveURL(/\/admin/);

        // 2. Navigate to Write/Editor page
        // Assuming there is a link or we verify by navigation
        await page.goto('/admin/editor');

        // 3. Write Article
        await page.fill('input[placeholder="Article Title"]', 'E2E Test Article');

        // Wait for categories to load if they are fetched async
        // We select the first option just to be safe
        const categorySelect = page.locator('select').nth(1); // Assuming 2nd select is category
        await expect(categorySelect).toBeVisible();
        await categorySelect.selectOption({ index: 0 });

        // Content is in Tiptap/ProseMirror, which is a contenteditable div
        const editor = page.locator('.ProseMirror');
        await editor.click();
        await editor.fill('This is a test article content generated by Playwright.');

        // 4. Publish
        // Handle alert dialog
        page.once('dialog', async dialog => {
            await dialog.accept();
        });

        await page.click('button:has-text("Publish")');

        // Expect to be redirected back to admin dashboard or stay (based on code checking earlier, it goes to /admin)
        await expect(page).toHaveURL(/\/admin/);
    });
});
